name: codeine
description: Music App CODEINE
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  html: ^0.15.0
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  connectivity_plus: ^2.0.3
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  snapping_sheet: ^3.1.0
  palette_generator: ^0.3.0
  animated_text_kit: ^4.2.1
  html_unescape: ^2.0.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/png/